services:
  db:
    image: postgres:15
    container_name: task-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  main-service:
    build: .
    container_name: main_service
    restart: always
    depends_on:
      - db
      - auth-service
      - tasks-service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskdb
    ports:
      - "8080:8080"


  auth-service:
    build: .
    container_name: auth_service
    restart: always
    working_dir: /app
    command: ["./auth"]
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskdb
    ports:
      - "8000:8000"

  tasks-service:
    build: .
    container_name: tasks_service
    restart: always
    working_dir: /app
    command: ["./tasks"]
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskdb
    ports:
      - "8001:8001"

volumes:
  postgres_data: